### ISSUE TITLE
Classifying other file types instead of Other.

### ISSUE THREAD

**Issue by timvoet** [mujx/hakatime#13]
Is there something we can do to help classify the "other" bucket of file types.

I currently have the templating files (ERB, SLIM, etc ) of my ruby projects classified as "other"

**Comment by mujx** [comment]
The classification is done by the wakatime client. In order for these languages to be recognized the client must support it.

**Comment by timvoet** [comment]
Waka time recognizes the others properly as ERB files. I just checked

**Comment by mujx** [comment]
It doesn't seem like it's supported from this list https://github.com/wakatime/wakatime/blob/a05026c791794bdd2530d0883f63d100d4f06b47/wakatime/languages/default.json. 

Probably the wakatime server extracts the language from the `.erb` extension, but the client doesn't seem to send the language name.

**Comment by timvoet** [comment]
I don't know what to say, they do classify it. https://snipboard.io/wPG8xQ.jpg

this was yesterday's session.
