### ISSUE TITLE
Unknown error when registering

### ISSUE THREAD

**Issue by jmangelson** [mujx/hakatime#15]
I am also running to problems when running the built in container generated via docker-compose-deploy.yml file. 

If I use the default configuration I am able to access the dashboard login page at localhost:8080, however when I attempt to register, I get "registration failed: unknown error".

**Comment by mujx** [comment]
Can you share some of the logs after the failed registration attempt? It might be related to #1 .

**Comment by jmangelson** [comment]
Here are the docker logs for both containers:

hakatime (dashboard) log:
172.18.0.1 - - [15/Dec/2020:18:38:35 +0000] "GET / HTTP/1.1" 200 1271880 "" "curl/7.68.0\
"
172.18.0.1 - - [15/Dec/2020:18:40:02 +0000] "GET / HTTP/1.1" 200 1271880 "" "curl/7.68.0\
"
172.18.0.1 - - [15/Dec/2020:18:57:09 +0000] "GET / HTTP/1.1" 200 1271880 "" "Mozilla/5.0\
 (X11; Ubuntu; Linux x86_64; rv:83.0) Gecko/20100101 Firefox/83.0"
172.18.0.1 - - [15/Dec/2020:18:57:09 +0000] "GET /images/favicon-16x16.65022224.png HTTP\
/1.1" 200 424 "http://localhost:8080/" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:83.0)\
 Gecko/20100101 Firefox/83.0"
172.18.0.1 - - [15/Dec/2020:18:57:09 +0000] "POST /auth/refresh_token HTTP/1.1" 400 - "h\
ttp://localhost:8080/" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:83.0) Gecko/20100101 \
Firefox/83.0"
172.18.0.1 - - [15/Dec/2020:18:57:09 +0000] "GET /nunito-latin-400.3a5373d7.woff2 HTTP/1\
.1" 200 20448 "http://localhost:8080/" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:83.0)\
 Gecko/20100101 Firefox/83.0"
172.18.0.1 - - [15/Dec/2020:18:57:09 +0000] "GET /images/apple-touch-icon.e9420083.png H\
TTP/1.1" 200 5710 "http://localhost:8080/" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:8\
3.0) Gecko/20100101 Firefox/83.0"
172.18.0.1 - - [16/Dec/2020:00:44:02 +0000] "GET / HTTP/1.1" 304 - "" "Mozilla/5.0 (X11;\
 Ubuntu; Linux x86_64; rv:83.0) Gecko/20100101 Firefox/83.0"
172.18.0.1 - - [16/Dec/2020:00:44:02 +0000] "GET /nunito-latin-400.3a5373d7.woff2 HTTP/1\
.1" 304 - "http://localhost:8080/" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:83.0) Gec\
ko/20100101 Firefox/83.0"
172.18.0.1 - - [16/Dec/2020:00:44:02 +0000] "POST /auth/refresh_token HTTP/1.1" 400 - "h\
ttp://localhost:8080/" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:83.0) Gecko/20100101 \
Firefox/83.0"
172.18.0.1 - - [16/Dec/2020:00:44:02 +0000] "GET /images/apple-touch-icon.e9420083.png H\
TTP/1.1" 200 5710 "http://localhost:8080/" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:8\
3.0) Gecko/20100101 Firefox/83.0"
172.18.0.1 - - [16/Dec/2020:00:44:26 +0000] "POST /auth/register HTTP/1.1" 400 - "http:/\
/localhost:8080/" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:83.0) Gecko/20100101 Firef\
ox/83.0"
172.18.0.1 - - [16/Dec/2020:00:46:03 +0000] "POST /auth/refresh_token HTTP/1.1" 400 - "h\
ttp://localhost:8080/" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:83.0) Gecko/20100101 \
Firefox/83.0"
172.18.0.1 - - [16/Dec/2020:00:46:03 +0000] "GET /images/apple-touch-icon.e9420083.png H\
TTP/1.1" 200 5710 "http://localhost:8080/" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:8\
3.0) Gecko/20100101 Firefox/83.0"
172.18.0.1 - - [16/Dec/2020:00:46:03 +0000] "GET /nunito-latin-400.3a5373d7.woff2 HTTP/1\
.1" 200 20448 "http://localhost:8080/" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:83.0)\
 Gecko/20100101 Firefox/83.0"
172.18.0.1 - - [16/Dec/2020:05:15:26 +0000] "POST /auth/register HTTP/1.1" 400 - "http:/\
/localhost:8080/" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:83.0) Gecko/20100101 Firef\
ox/83.0"

--------------------------------------------------------------------------------
haka_db (postgres:11-alpine) log:
Data page checksums are disabled.

fixing permissions on existing directory /var/lib/postgresql/data ... ok
creating subdirectories ... ok
selecting default max_connections ... 100
selecting default shared_buffers ... 128MB
selecting default timezone ... UTC
selecting dynamic shared memory implementation ... posix
creating configuration files ... ok
running bootstrap script ... ok
performing post-bootstrap initialization ... ok
syncing data to disk ... ok

Success. You can now start the database server using:

    pg_ctl -D /var/lib/postgresql/data -l logfile start

waiting for server to start....2020-12-15 18:26:47.717 UTC [35] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
2020-12-15 18:26:47.735 UTC [36] LOG:  database system was shut down at 2020-12-15 18:26:47 UTC
2020-12-15 18:26:47.738 UTC [35] LOG:  database system is ready to accept connections
 done
server started
CREATE DATABASE


/usr/local/bin/docker-entrypoint.sh: running /docker-entrypoint-initdb.d/001-init.sql
BEGIN
CREATE TABLE
CREATE TABLE
CREATE TABLE
CREATE TABLE
CREATE TABLE
COMMIT


/usr/local/bin/docker-entrypoint.sh: running /docker-entrypoint-initdb.d/002-datetime-index.sql
CREATE INDEX


/usr/local/bin/docker-entrypoint.sh: running /docker-entrypoint-initdb.d/003-create-badges.sql
CREATE EXTENSION
CREATE TABLE


waiting for server to shut down....2020-12-15 18:26:48.206 UTC [35] LOG:  received fast shutdown request
2020-12-15 18:26:48.208 UTC [35] LOG:  aborting any active transactions
2020-12-15 18:26:48.210 UTC [35] LOG:  background worker "logical replication launcher" (PID 42) exited with exit code 1
2020-12-15 18:26:48.210 UTC [37] LOG:  shutting down
2020-12-15 18:26:48.245 UTC [35] LOG:  database system is shut down
 done
server stopped

PostgreSQL init process complete; ready for start up.
----------------------------------------------------------------------------------------

**Comment by jmangelson** [comment]
docker ps shows both containers running:

CONTAINER ID   IMAGE                  COMMAND                  CREATED        STATUS        PORTS                      NAMES
ce078409ad90   mujx/hakatime:latest   "/app/bin/hakatime r…"   11 hours ago   Up 11 hours   127.0.0.1:8080->8080/tcp   hakatime
2cd61a78238b   postgres:11-alpine     "docker-entrypoint.s…"   11 hours ago   Up 11 hours   5432/tcp                   haka_db

**Comment by jmangelson** [comment]
ok, this seems to be working now under a couple conditions:

1. I added myself to the docker group so that I am no longer rundding docker using sudo
2. The HAKA_CORS_URL must match exactly what I use to access the site. 

I've also only got it to work when the HAKA_CORS_URL string includes the port number and only when it is localhost:8080 or localhost:8090

**Comment by jmangelson** [comment]
Is there some way of getting this to work without the port included in the URL?

**Comment by mujx** [comment]
It would be possible if CORS is disabled from the service, but that's not currently implemented.
