### ISSUE TITLE
tagged docker releases

### ISSUE THREAD

**Issue by luckydonald** [mujx/hakatime#17]
It would be great if one could pin the docker release to do be able to run updates intentionally.

Could be as simple as a commit hash, date, or a semvar

**Comment by mujx** [comment]
Will release a `v1.0.0` soon enough, now that the database schema has been stabilized. Keep in mind that there might be backwards incompatible changes.

**Comment by luckydonald** [comment]
That's great.

Tagging nightly `latest` (aka the newest git version) builds with a commit hash or date would be still be beneficial, for those who want to live on the edge or try out a feature with the option to go back just a bit.

**Comment by mujx** [comment]
Closing this now that `v1.0.0` is out. From now on the project will have tagged releases along with the `latest` tag on every commit.
