### ISSUE TITLE
Non-unicode database names fail

### ISSUE THREAD

**Issue by luckydonald** [mujx/hakatime#18]
Apparently I can't use a database name like `﹍hakatime`.

```
[2021-01-30 23:50:14][hakatime.server][Error][9b15e04cdb0a][PID 1][ThreadId 47][hakatime-0.1.0-inplace-libhaka:Haka.Errors src/Haka/Errors.hs:126:5]
OperationException "ConnectionError (Just \"FATAL:  database \\\"Mhakatime\\\" does not exist\\n\")"
```
It is correctly in the docker-inspect.
<details><summary><img width="263" alt="image" src="https://user-images.githubusercontent.com/2737108/106370862-8e469c80-635e-11eb-8d3d-ee3f2a92218c.png"> <I>click to display code</I></summary>

```
 },
            "Tty": false,
            "OpenStdin": false,
            "StdinOnce": false,
            "Env": [
                "HAKA_DB_HOST=postgres",
                "HAKA_DB_PORT=5432",
                "HAKA_DB_NAME=﹍hakatime",
```
</details>

`exec`-ing into the container and echoing that variable is shown correctly there too.
<details><summary><img width="376" alt="image" src="https://user-images.githubusercontent.com/2737108/106370898-f8f7d800-635e-11eb-8ea2-3b14e09df774.png"> <I>click to display code</I>
</summary>

```
luckydonald$ d-c exec hakatime /bin/sh
/ # echo $HAKA_DB_NAME
﹍hakatime
```
</details>

The database was created successfully, and the sql files in /docker loaded.

<img width="363" alt="image" src="https://user-images.githubusercontent.com/2737108/106371017-0497ce80-6360-11eb-852e-f5c6b6c025f0.png">

Therefore this seems to be a problem with hakatime.

**Comment by mujx** [comment]
Thanks a lot for the bug report!
