### ISSUE TITLE
ARM Docker image not updated

### ISSUE THREAD

**Issue by FredrikMeyer** [mujx/hakatime#21]
First, thanks for this app!

I've had it working on my Pi for a long time now, and I saw you had done some updates. So I was thinking to try to update. I would think the way to do it was to update the Docker compose file (refering to the newest ARM image and add the config options in the last updates), but I see the latest ARM image is 5 months old.

So I tried building it myself. (`docker build -f Dockerfile.arm .` inside the Pi). That failed however:
```
Step 18/30 : RUN cabal build -j2 --dependencies-only exe:hakatime
 ---> Running in 6936a8e6b364
cabal: unrecognized 'build' option `--dependencies-only'
```

I did some Googling, but I'm not very familiar with the Haskell ecosystem so I gave up.

So for now I just use the latest ARM image with my old config.

**Comment by mujx** [comment]
The current dockerfile for ARM is configured incorrectly with the wrong base image which has an old version of cabal. Replacing the base image with `ubuntu:20.10` might work (I'm currently testing this).

The problem with ARM is that the upstream docker images have quite outdated versions of the build tools needed. The old setup was relying on an unstable debian image which unfortunately started failing on qemu (virtualization layer I used to cross compile the images). Another issue is the lack of ARM builders on CI services. I'm using travis to update the docker tags but it started stalling lately and the builds were killed.

**Comment by mujx** [comment]
Updated the arm dockerfile and now you can actually run the latest version. The issue left is with the Travis build which keeps stalling (https://travis-ci.org/github/mujx/hakatime/builds/759900305)

**Comment by FredrikMeyer** [comment]
Thank you! I'll give it a try later today and update how it went!

**Comment by mujx** [comment]
Managed to actually push the build to dockerhub.

**Comment by mujx** [comment]
Closing now that the dockerfile builds again. Please re-open is you encounter any issues.

**Comment by FredrikMeyer** [comment]
Sorry, for the late answer - I got time today to try the newest ARM image. Unfortunately I couldn't get it to work. I also tried building the ARM image on the Pi, but that failed:
```
Step 19/29 : RUN cabal build -j2 exe:hakatime && mkdir -p /app/bin &&     cp /build/dist-newstyle/build/*-linux/ghc-*/hakatime-*/x/hakatime/opt/build/hakatime/hakatime /app/bin/hakatime
 ---> Running in a3a675030616
Package has never been configured. Configuring with default flags. If this
fails, please run configure manually.
cabal: hakatime.cabal:48: 'library' expects no argument
The command '/bin/sh -c cabal build -j2 exe:hakatime && mkdir -p /app/bin &&     cp /build/dist-newstyle/build/*-linux/ghc-*/hakatime-*/x/hakatime/opt/build/hakatime/hakatime /app/bin/hakatime' returned a non-zero code: 1
```

The error message for Docker compose is this:
```
pi@raspberrypi:/hakatime $ docker-compose -f docker-compose-deploy.yml up
Starting hakatime ... done
Starting haka_db  ... done
Attaching to haka_db, hakatime
haka_db    |
haka_db    | PostgreSQL Database directory appears to contain a database; Skipping initialization
haka_db    |
haka_db    | 1970-05-06 12:44:24.010 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
haka_db    | 1970-05-06 12:44:24.010 UTC [1] LOG:  listening on IPv6 address "::", port 5432
haka_db    | 1970-05-06 12:44:24.010 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
hakatime   | standard_init_linux.go:219: exec user process caused: exec format error
hakatime exited with code 1
haka_db    | 1970-05-06 12:44:24.010 UTC [1] LOG:  startup process (PID 22) was terminated by signal 11: Segmentation fault
haka_db    | 1970-05-06 12:44:24.010 UTC [1] LOG:  aborting startup due to startup process failure
haka_db    | 1970-05-06 12:44:24.010 UTC [1] LOG:  database system is shut down
haka_db exited with code 1
```

I think I recall that `exec format error` often comes when the image is for the wrong architecture, but I double-checked that I actually pull the right image: `    image: mujx/hakatime:latest-arm`

**Comment by mujx** [comment]
Are you on arm64? It seems that your system is on armv7.

**Comment by FredrikMeyer** [comment]
Hm, I just checked! Turns out I run on armv7, yes. 

I have been running Hakatime on the same Raspberry Pi since september, so I  didn't think architecture would be a problem.

**Comment by mujx** [comment]
The problem seems to be that I uploaded the arm64 version instead of armv7 as you can see in the [docker tags](https://hub.docker.com/r/mujx/hakatime/tags?page=1&ordering=last_updated).

Of course the problem remains why it doesn't build locally.

**Comment by mujx** [comment]
@FredrikMeyer Could you try building it again? I removed that argument that it complained about.

**Comment by FredrikMeyer** [comment]
@mujx So this time I came longer :P. 

On my first try I got this message:
```
 ---> 7f31dc81a02a
Step 9/31 : RUN apt-get update -y -qq &&     apt-get install --no-install-recommends -y curl ghc cabal-install libffi-dev libpq-dev libgmp-dev zlib1g-dev
 ---> Running in 2072464e0f4d
W: GPG error: http://ports.ubuntu.com/ubuntu-ports groovy InRelease: At least one invalid signature was encountered.
E: The repository 'http://ports.ubuntu.com/ubuntu-ports groovy InRelease' is not signed.
W: GPG error: http://ports.ubuntu.com/ubuntu-ports groovy-updates InRelease: At least one invalid signature was encountered.
E: The repository 'http://ports.ubuntu.com/ubuntu-ports groovy-updates InRelease' is not signed.
W: GPG error: http://ports.ubuntu.com/ubuntu-ports groovy-backports InRelease: At least one invalid signature was encountered.
E: The repository 'http://ports.ubuntu.com/ubuntu-ports groovy-backports InRelease' is not signed.
W: GPG error: http://ports.ubuntu.com/ubuntu-ports groovy-security InRelease: At least one invalid signature was encountered.
E: The repository 'http://ports.ubuntu.com/ubuntu-ports groovy-security InRelease' is not signed.
The command '/bin/sh -c apt-get update -y -qq &&     apt-get install --no-install-recommends -y curl ghc cabal-install libffi-dev libpq-dev libgmp-dev zlib1g-dev' returned a non-zero code: 100
```

And some Googling showed that Raspbian had some outdated package (see Appendix here http://unixetc.co.uk/2020/04/24/install-docker-on-raspberry-pi/). So I updated `libseccomp` and tried again.

This time it started building, and it did so for about an hour. Then I got this message:
```
Installing   data-dword-0.3.2 (lib)
Completed    data-dword-0.3.2 (lib)
Building     postgresql-libpq-0.9.4.3 (all, legacy fallback)
Installing   postgresql-libpq-0.9.4.3 (all, legacy fallback)
Completed    postgresql-libpq-0.9.4.3 (all, legacy fallback)
cabal: Failed to build haskell-src-exts-1.23.1 (which is required by
exe:hakatime from hakatime-1.0.1). The build process was killed (i.e.
SIGKILL). The typical reason for this is that there is not enough memory
available (e.g. the OS killed a process using lots of memory).

The command '/bin/sh -c cabal configure --disable-optimization &&     cabal build -j2 exe:hakatime && mkdir -p /app/bin &&     cp /build/dist-newstyle/build/*-linux/ghc-*/hakatime-*/x/hakatime/opt/build/hakatime/hakatime /app/bin/hakatime' returned a non-zero code: 1
```

Seems like some memory issues with Docker. I got the same message yesterday when I tried building on my Mac with `buildx`.

**Comment by mujx** [comment]
Cross-compiling with buildx is unfortunately painfully slow. You could try replacing `-j2` with `-j1` on the dockerfile to make it use a single process.

**Comment by mujx** [comment]
@FredrikMeyer: You can also try with `optimization: 0` [here](https://github.com/mujx/hakatime/blob/f1ee44f8c27298c93fc98dd81f12f9e8043516e8/cabal.project#L5) which will speed up things significantly and consume a lot less memory.

The performance should be practically the same.

**Comment by mujx** [comment]
Good news! CircleCI started offering ARM builders so now we have automated CI builds for arm64 docker images with the tag `latest-arm`. Will soon update the CI to include tagged releases.

Will close this one now that the ARM builds are up-to-date again.
