### ISSUE TITLE
Issue With project_tags Creation

### ISSUE THREAD

**Issue by jimmybrancaccio** [mujx/hakatime#26]
Hello!

I am using `mujx/hakatime:latest` and have been using this image for at least 3-4 weeks now. The container seems to be having some issues. In the logs I see:

```
Waiting for the PostgreSQL service to become available ...,
Connected to PostgreSQL,
Database hakatime already exists,
NOTICE:  relation "schema_migrations" already exists, skipping,
NOTICE:  relation "tags" already exists, skipping,
Running migrations from files found in /app/migrations,
Initializing schema,
Migrations schema initialized,
hakatime: SqlError {sqlState = "42830", sqlExecStatus = FatalError, sqlErrorMsg = "there is no unique constraint matching given keys for referenced table \"projects\"", sqlErrorDetail = "", sqlErrorHint = ""}
```

So I tried running the query manually and I got the same error:

<img width="1213" alt="Screen Shot 2021-03-06 at 20 11 40" src="https://user-images.githubusercontent.com/405585/110226871-2da80380-7eb8-11eb-8cf4-b0e189144079.png">

Unfortunately I don't know enough about PGSQL and queries to know what the issue here is 😢 so any help on fixing this would be awesome 😬 !

**Comment by mujx** [comment]
Were you using the image before `v1.0.0`? It seems that you're missing some schema changes. Before `v1.0.0` schema migrations would have to be made manually but now they are automatic.

To add the missing schemas do the following:

- Take a backup of your database.
- Delete duplicate heartbeats with the following sql query:
```sql
DELETE FROM heartbeats a USING heartbeats b
WHERE a.id < b.id
    AND a.time_sent = b.time_sent
    AND a.sender = b.sender
    AND a.entity = b.entity;
```
- Set the `owner` field to your username (it should be `null`)
```sql
UPDATE projects SET owner = '<replace-with-your-hakatime-username>';
```
- Run the queries found [here](https://github.com/mujx/hakatime/tree/df869e2b9c1cecbc6ef9843b0b8f65525fd08137/docker) from `002` to `005`. It's ok if they get skipped with `relation <relation_name> already exists`.
- You can now run the versions after `v1.0.0`.

**Comment by jimmybrancaccio** [comment]
@mujx Ah yup! Those steps seemed to do the trick. Apologies on my part for not advising I had been running it pre-1.0.0! I had thought I caught all the updates to get to 1.0.0+ as I had to do some manual work to get some of the new heartbeat (de-duplication) stuff working myself. I appreciate your help in getting me back up and running! 😁

**Comment by mujx** [comment]
No worries @jimmybrancaccio, I'm glad you're up and running again!
