### ISSUE TITLE
Explanation for cut-off limit

### ISSUE THREAD

**Issue by williamboman** [mujx/hakatime#28]
Hey! I never really understood what the Cut-off limit is, and I have a feeling I'm not alone. I think it'd be nice with some explanation in the UI :). Thanks for this software btw! Just upgraded from <v1 to v1.2.0

**Comment by mujx** [comment]
Thanks a lot for using Hakatime! I will add a tooltip with the explanation on the UI.

The explanation is mentioned [here](https://wakatime.com/faq#timeout) in the wakatime website.

> Your timeout preference is the maximum time allowed between durations when calculating your total coding activity for a day. Think of it like a granularity setting. It can’t make you code more or less, it just combines durations with more or less accuracy.
>
>For ex, if you typed code for 2 mins, took a 13 min break, then typed code for 1 min:
>
> - 10 min timeout: Your dashboard shows 3 mins of coding activity (2 mins + 1 min).
> - 5 min timeout (default): Your dashboard shows 16 mins of coding activity (2 mins + 13 min break + 1 min).
> - 30 min timeout: Your dashboard still shows 16 mins of coding activity (2 mins + 13 min break + 1 min; the timeout preference only affects time between heartbeats not surrounding).

Maybe `timeout` is a better name for it?

**Comment by mujx** [comment]
@williamboman Check out the demo instance, hopefully now it's a bit more clear. 

Any other suggestions are highly welcome. Especially around charts/analytics :)

**Comment by williamboman** [comment]
> The explanation is mentioned [here](https://wakatime.com/faq#timeout) in the wakatime website.

Ah, I did not think of searching Wakatime docs for explanations. Their explanation makes perfect sense.



> Thanks a lot for using Hakatime! I will add a tooltip with the explanation on the UI.

Was this added? I can't seem to trigger the tooltip when using the demo instance 🤔

**Comment by mujx** [comment]
You can trigger it if you hover over the icon.

**Comment by williamboman** [comment]
> You can trigger it if you hover over the icon.

Aah I didn't realize I had to hover the icon, even after reading your comment 🙈. Found it now! Thanks :)
