### ISSUE TITLE
Badge for certain timespans

### ISSUE THREAD

**Issue by Butzlabben** [mujx/hakatime#29]
Hi,

I would like to request a feature. It would be nice to generate badges also for certain timespans. It would be nice to publicly display for example for how long you have worked on a project in general.

P.S.: Is there a way donate money to the author? I want to support this project as I like it really much.

**Comment by mujx** [comment]
Hi @Butzlabben, 

Thanks a lot for using hakatime. Currently there is a query param called `days` that you can change on your generated badge. This will you give the total time spent on the project in the last N days.
```
https://hakatime-demo.mtx-dev.xyz/badge/svg/f8c0f834-3747-4d3f-965b-6fa08c6dea94?days=90
```
Would you like to have something like a `from` & `to` parameters to control the timespan?

I will try to setup something for donations.

**Comment by Butzlabben** [comment]
The amount of days will be enough for me. Thanks for helping.
