### ISSUE TITLE
Project aliases

### ISSUE THREAD

**Issue by MDXDave** [mujx/hakatime#32]
Some of my projects are tracked as 2 projects because they have different folder names on my Macbook and my Windows PC. 
Maybe its possible to add the possibility to allow adding an alias for the project under which the two projects got bundled ([Wakapi](https://github.com/muety/wakapi) implements this possibility).

**Comment by mujx** [comment]
You can use tags on those projects to view their aggregated data as an alternative for now.

**Comment by mujx** [comment]
You can now set a tag on both projects `e.g alias:my-app` (or any other name) and you can view their aggregated statistics.
