### ISSUE TITLE
Heartbeats importing doesn't work

### ISSUE THREAD

**Issue by allanvb** [mujx/hakatime#33]
I tried to import the data from wakatime.
I provided and api key from wakatime wich is valid, and I got the toast saying that importing job has started. 
Despite this the data aren't fetched. 
If I open the browser console, i see a repeating request to the `import/status` endpoint, and the response is always `jobStatus: "JobPending"`. 
As a date range I selected two days 21 apr - 22 apr.
I also tried to restart docker containers but nothing changed

**Comment by mujx** [comment]
Do you have any logs from the server?

**Comment by allanvb** [comment]
> Do you have any logs from the server?
I will try to export logs a bit later. It wont work and no matters wich range i choose

**Comment by allanvb** [comment]
@mujx I tried today and everything works fine. I don't know what was the problem. Can it be related to wakatime bug ?

**Comment by mujx** [comment]
I was not able to reproduce locally. Maybe it was some network issue?
