### ISSUE TITLE
Postgresql db upgrade failing

### ISSUE THREAD

**Issue by Miladiir** [mujx/hakatime#39]
As you can see from the logs, sql migration is failing on postgresql 9.6, where it was working previously. I am running both hakatime and postgres with docker and using a non super user with postgres. The sql user "hakatime" only has acces to this one db.

```
Database hakatime already exists
NOTICE:  relation "schema_migrations" already exists, skipping
hakatime: SqlError {sqlState = "42883", sqlExecStatus = FatalError, sqlErrorMsg = "function uuid_generate_v4() does not exist", sqlErrorDetail = "", sqlErrorHint = "No function matches the given name and argument types. You might need to add explicit type casts."}
Running migrations from files found in /app/migrations
Initializing schema
Migrations schema initialized
HAKA_DB_HOST: postgres
HAKA_DB_PORT: 5432
HAKA_DB_USER: hakatime
HAKA_DB_NAME: hakatime
Waiting for the PostgreSQL service to become available ...
Connected to PostgreSQL
Database hakatime already exists
NOTICE:  relation "schema_migrations" already exists, skipping
hakatime: SqlError {sqlState = "42883", sqlExecStatus = FatalError, sqlErrorMsg = "function uuid_generate_v4() does not exist", sqlErrorDetail = "", sqlErrorHint = "No function matches the given name and argument types. You might need to add explicit type casts."}
Running migrations from files found in /app/migrations
Initializing schema
Migrations schema initialized
```

**Comment by mujx** [comment]
Could you give some more information about the commands you were running?

You were migrating from what version?

What do you see in the server logs?

**Comment by Miladiir** [comment]
> Could you give some more information about the commands you were running?

```
docker stop hakatime && docker rm hakatime
docker pull mujx/hakatime:latest
docker run -d --name hakatime \
  -e "HAKA_DB_HOST=postgres" \
  -e "HAKA_DB_PORT=5432" \
  -e "HAKA_DB_NAME=XXX" \
  -e "HAKA_DB_PASS=XXX" \
  -e "HAKA_DB_USER=XXX" \
  -e "HAKA_CORS_URL=XXX" \
  -e "HAKA_PORT=8080" \
  mujx/hakatime:latest
```
As I said, I am running this dockerized and did not run anything special. I guess the migration is triggered by the app itself.

> You were migrating from what version?

Sorry, but I really have no idea. The old image seems to be unpinned. I guess this is on me for trying to pull latest and not another pinned image.

> What do you see in the server logs?

Those are the docker container logs of hakatime. In my volumes, I cannot find anything that looks like hakatime logs, so I guess thats it.

One pointer I have that `uuid_generate_v4()` may not be available when not running as a super user, which the postgre user for hakatime definitely is not.

**Comment by mujx** [comment]
@Miladiir It seems that you were indeed running a version prior to `1.0.0` and migrations cannot be performed automatically.

Check this  https://github.com/mujx/hakatime/issues/26#issuecomment-792242314 on how to migrate to the `1.x` series.

**Comment by Miladiir** [comment]
Sorry, that issue did not come up in my search. I will perform the migration. Thank you. This can be closed.
