### ISSUE TITLE
Can't run the hakatime service on a raspberry pi

### ISSUE THREAD

**Issue by timvoet** [mujx/hakatime#5]
I tried to setup and run hakatime on my Raspberry pi with docker.  The DB runs just fine, but hakatime won't start and i get the following error

standard_init_linux.go:211: exec user process caused "exec format error"

I don't think it's anything related to the app, but the docker images selected.

**Comment by mujx** [comment]
Self-hosting hakatime in a RPi is a great use-case! I'll look into [buildx](https://github.com/docker/buildx#building-multi-platform-images)/[buildkit](https://github.com/moby/buildkit) for a way to build arm images.

**Comment by timvoet** [comment]
Let me know if there is anything I can do. I love the idea of this project.  Paired with a nice VPN connection to my PI, seems like the perfect solution.

**Comment by mujx** [comment]
@timvoet I've pushed some arm images with `test` tag (https://hub.docker.com/repository/docker/mujx/hakatime/tags?page=1). Could you check if they are working? (I don't have an RPi myself)

**Comment by timvoet** [comment]
new error
hakatime   | standard_init_linux.go:211: exec user process caused "exec format error"

**Comment by mujx** [comment]
@timvoet Apologies, the last image was still amd64. I've managed to build some proper arm images with the tag `latest-arm`.

Unfortunately building an arm image on a non arm machine, goes through qemu and in hakatime's case, a full build it's painfully slow (several hours). So it might not be possible to provide an automated ci build without an arm machine, but I'll try to upload them manually once in a while. There is an arm specific dockerfile (`Dockerfile.arm`) so you can build it yourself as a last resort.

**Comment by timvoet** [comment]
No worries, i've been messing around trying to get it to build locally on my PI, but it fails with the current Dockerfile.  So far I've had signature issues with the debian:testing image, moved to stable:slim, and cabal doesn't recognize the "--dependencies-only flag

I'll keep trying this week, maybe I'll have some luck.

**Comment by mujx** [comment]
It's probably an older version of cabal. You can remove that line entirely, it's only there for cache purposes. You also might want to to add `-j1` on `cabal build exe:hakatime` in case the build fails with an OOM exception.

**Comment by mujx** [comment]
Closing, because now there is a Dockerfile for ARM.

**Comment by timvoet** [comment]
still doesn't build on a PI, and the ARM images don't run.  you closed the ticket, i guess it was worth a try.

**Comment by mujx** [comment]
@timvoet What is the ARM architecture of your pi? (which model etc). Could you paste here the errors you encountered? 

There is support for the `arm/v7` & `arm64` architectures.

**Comment by timvoet** [comment]
latest repo version gives this error when trying to start up

standard_init_linux.go:211: exec user process caused "exec format error"
standard_init_linux.go:211: exec user process caused "exec format error"

RaspberryPI 4b
4 GB ram
revision: c03112
OS: Rasbian
Release: 10 (Buster)

**Comment by mujx** [comment]
@timvoet That error means that you're using an image of a different architecture.

Did you try `mujx/hakatime:latest-arm` or `mujx/hakatime:latest`?

The image with the `latest-arm` tag is the one that is supposed to support your architecture.

**Comment by timvoet** [comment]
i changed the line from the docker compose
services:
  server:
    container_name: hakatime
    image: mujx/hakatime:latest-arm

i pulled the latest repository

i ran docker-compose -f docker-compose-deploy.yml up -d
running docker-compose -f docker-compose-deploy.yml start gives an error, and this is the contents of the log files

Attaching to haka_db, hakatime
haka_db    |
haka_db    | PostgreSQL Database directory appears to contain a database; Skipping initialization
haka_db    |
haka_db    | 2020-09-28 18:04:56.653 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
haka_db    | 2020-09-28 18:04:56.653 UTC [1] LOG:  listening on IPv6 address "::", port 5432
haka_db    | 2020-09-28 18:04:56.667 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
haka_db    | 2020-09-28 18:04:56.735 UTC [20] LOG:  database system was shut down at 2020-09-28 18:01:33 UTC
haka_db    | 2020-09-28 18:04:56.750 UTC [1] LOG:  database system is ready to accept connections
hakatime   | standard_init_linux.go:211: exec user process caused "exec format error"

**Comment by mujx** [comment]
@timvoet Could you verify that the binary located in `/app/bin/hakatime` is actually for the ARM architecture. You can try the following:

```bash
docker run --rm --entrypoint cat mujx/hakatime:latest-arm /app/bin/hakatime > ./hakatime
file ./hakatime
```

**Comment by timvoet** [comment]
pi@raspberrypi:~/docker_projects/hakatime $ docker run --rm --entrypoint cat mujx/hakatime:latest-arm /app/bin/hakatime > ./hakatime
standard_init_linux.go:211: exec user process caused "exec format error"
pi@raspberrypi:~/docker_projects/hakatime $ file ./hakatime
./hakatime: empty
pi@raspberrypi:~/docker_projects/hakatime $

**Comment by mujx** [comment]
The command still didnt run. What is the issue if you try to build it yourself?

You can try with the postgres image, to see the arch
```
docker run --rm --entrypoint cat postgres:11 /usr/lib/postgresql/11/bin/postgres > ./postgres
file postgres
```

**Comment by timvoet** [comment]
the postgres runs fine, see below.

./postgres: ELF 32-bit LSB shared object, ARM, EABI5 version 1 (SYSV), dynamically linked, interpreter /lib/ld-linux-armhf.so.3, for GNU/Linux 3.2.0, BuildID[sha1]=4dc11e286c63b54229d899287bdb17fd2e1ea281, stripped

I can't build locally because of the cabal issues I shared earlier.

**Comment by mujx** [comment]
That's weird.

You can try building again, I've updated the Dockerfile. What kind of signature issues?

**Comment by timvoet** [comment]
It is weird, i have no ideas

docker-compose ps produces the following

pi@raspberrypi:/docker_projects/hakatime $ docker-compose -f docker-compose-deploy.yml ps
  Name                Command              State     Ports
------------------------------------------------------------
haka_db    docker-entrypoint.sh postgres   Up       5432/tcp
hakatime   /app/bin/hakatime run           Exit 1

docker-compose logs produces the following
hakatime   | standard_init_linux.go:211: exec user process caused "exec format error"

i changed the docker-compose-deploy.yml to this (this is the ONLY change I made to the file, as per your instructions )
image: mujx/hakatime:latest-arm

**Comment by timvoet** [comment]
and if i try to build the image myself from the Docker.arm-deps
pi@raspberrypi:~/docker_projects/hakatime $ docker build -f Dockerfile.arm-deps .
Sending build context to Docker daemon  2.404MB
Step 1/14 : FROM debian:testing-slim as server-builder
 ---> 55d8fd1d7a49
Step 2/14 : WORKDIR /build
 ---> Using cache
 ---> 48d28fa0d211
Step 3/14 : RUN apt-get update -y -qq &&     apt-get install -y ghc cabal-install libffi-dev libgmp-dev libncurses-dev libpq-dev zlib1g-dev llvm
 ---> Running in de882e314cfa
W: GPG error: http://deb.debian.org/debian testing InRelease: At least one invalid signature was encountered.
E: The repository 'http://deb.debian.org/debian testing InRelease' is not signed.
The command '/bin/sh -c apt-get update -y -qq &&     apt-get install -y ghc cabal-install libffi-dev libgmp-dev libncurses-dev libpq-dev zlib1g-dev llvm' returned a non-zero code: 100

and when I run with docker build -f Docker.arm .
Step 14/25 : COPY test/          ./test
 ---> 7a2e9a2dd576
Step 15/25 : COPY tools/         ./tools
 ---> 7ea2365b49b6
Step 16/25 : RUN cabal build exe:hakatime && mkdir -p /app/bin &&     cp /build/dist-newstyle/build/*-linux/ghc-*/hakatime-*/x/hakatime/opt/build/hakatime/hakatime /app/bin/hakatime
 ---> Running in 771c119c1e34
clock_gettime: Operation not permitted
The command '/bin/sh -c cabal build exe:hakatime && mkdir -p /app/bin &&     cp /build/dist-newstyle/build/*-linux/ghc-*/hakatime-*/x/hakatime/opt/build/hakatime/hakatime /app/bin/hakatime' returned a non-zero code: 1

**Comment by FredrikMeyer** [comment]
@timvoet I got it to work on my Raspberry Pi 4. I also had the same issue as you (`clock_gettime: Operation not permitted`). See my issue: https://github.com/mujx/hakatime/issues/10 for how I solved it :)

**Comment by timvoet** [comment]
works great now.

**Comment by mujx** [comment]
I'll close this issue in favor of #10 , which describes the `clock_gettime: Operation not permitted` problem.
