### ISSUE TITLE
Demo is down :-)

### ISSUE THREAD

**Issue by cocoonkid** [mujx/hakatime#53]
Demo is down :-)

**Comment by mujx** [comment]
Yeah, Sorry about that, my cloud provider has issues. Will be back up shortly.

**Comment by kotx** [comment]
Seems to still be down..?

**Comment by mujx** [comment]
@cocoonkid @kotx The instance is now back online at hakatime.mtx-dev.xyz with open registration. Apologies for the delay.

**Comment by arsh-b** [comment]
Down again, anything we can do to help?

**Comment by mujx** [comment]
Sorry about that, it's best effort to keep up the service because there is no monitoring in place.
