### ISSUE TITLE
Activity per hour of day - no time allocated for 23-00

### ISSUE THREAD

**Issue by williamboman** [mujx/hakatime#56]
Hello! I have data on my Hakatime instance going back to 2020, and when I'm looking in the Projects view, in the "Activity per hour of day" chart there's never any hours allocated to 23 (11 PM) - it's 0 all the time. I found this to be a bit odd, maybe it's an off-by-one error somewhere?

**Comment by ablearthy** [comment]
Yeah! There's off-by-one error made [here](https://github.com/mujx/hakatime/blob/master/dashboard/src/utils.js#L67).

By the way, I have a question: what if `getTimezoneOffset` returns a positive value (e.g. `off = 2`)? Then for `v = 0`,  `(0 - (off)) % 24 = -2`. I think, it should be fixed too.
