### ISSUE TITLE
Badge all project

### ISSUE THREAD

**Issue by gunter423** [mujx/hakatime#67]
Hi,

Can we create a badge which combine all hourly time spent per project ? Like wakatime

Have nice day :)

**Comment by gunter423** [comment]
any news ?

**Comment by mujx** [comment]
Hi @gunter423 , I believe I'll take a look at this in the coming week.

**Comment by gunter423** [comment]
Hi @mujx,

Mmh, Can i develop this feature ?

**Comment by mujx** [comment]
Yes @gunter423, feel free to do so.

**Comment by gunter423** [comment]
Okay thanks,

I'll try to integrate this feature in few day :+1:
