### ISSUE TITLE
Import data from wakatime

### ISSUE THREAD

**Issue by tskulbru** [mujx/hakatime#7]
Would be nice if we could export the activity from wakatime and import them into hakatime so the users get a more "complete" timeline. Wakatime has a export function and tool which can export to different formats already.

**Comment by mujx** [comment]
Yes, that would be a nice feature. Do we know the export format for wakatime? (fields etc)

**Comment by allanvb** [comment]
I'm supporting @tskulbru idea.
Answering on your question, yes, we do. If you have some wakatime account with data in in then you can go to [Wakatime Settings](https://wakatime.com/settings/account) page and click export. This action will create a dump of ALL your data stored in wakatime account, so this will be a good feature that will allow users to have their old data in hacatime dashboard

**Comment by mujx** [comment]
Hi @allanvb. The problem with the exported data is that it only contains summary of the activity and not the actual timestamps received by the cluster. That means that some graphs won't be available in hakatime (like the ones separating activity by time of day etc)

**Comment by allanvb** [comment]
@mujx maybe we could store imported data in their own tables, or somewhere else, and to add a new page to dashboard for it where user will can get graphics only from imported data.

**Comment by alanhamlett** [comment]
> The problem with the exported data is that it only contains summary of the activity and not the actual timestamps received by the cluster.

That's right. You need to use the [Heartbeats API endpoint](https://wakatime.com/developers#heartbeats) to get the raw data. First, get the [user's created_at time](https://wakatime.com/developers#users). Then, loop through each day from then until now fetching each date's heartbeats.

**Comment by luckydonald** [comment]
Wouldn't it be quite easy to write like a python script loading the data from one server and shoving it into another, as long as the APIs are there?

**Comment by muety** [comment]
> Wouldn't it be quite easy to write like a python script loading the data from one server and shoving it into another, as long as the APIs are there?

Yes, should be more or less a no-brainer. However, right now, only exports in the direction of `WakaTime --> Hakatime` and `WakaTime --> Wakapi` will work, as neither Hakatime nor Wakapi expose an API to get raw heartbeats, yet.

**Comment by mujx** [comment]
@tskulbru @allanvb @luckydonald You can now import your data from Wakatime through the UI. I'll probably make it available as a CLI command also.

@alanhamlett Thanks for the hint! The only issue is that some fields are not resolved and the internal `id` is returned instead. (e.g `user_agent`, `machine`).

N.B: Due to some schema changes you'll have to remove duplicate heartbeats manually (in case you have an active instance). I've used the following query on my own instance. Duplicate entries are not allowed from on.
```SQL
DELETE FROM heartbeats a USING heartbeats b
WHERE a.id < b.id
    AND a.time_sent = b.time_sent
    AND a.project = b.project
    AND a.branch = b.branch
    AND a.machine = b.machine
    AND a.sender = b.sender
    AND a.entity = b.entity
    AND a.user_agent = b.user_agent;
```

**Comment by allanvb** [comment]
@mujx very nice update. Thank you.

**Comment by tskulbru** [comment]
Great work!

**Comment by alanhamlett** [comment]
Related, we've opened the API for all date ranges. You can import Heartbeats for non-Premium users back until their account was created. Dates before the user was created will just always return zero seconds.

Only the dashboard now limits date range queries, not the API 😄

**Comment by allanvb** [comment]
>  can import Heartbeats for non-Premium users back until their account was created. 

I noticed that a few weeks ago, but I thought this is just a forgotten validation on endpoint :D

**Comment by justin-jiajia** [comment]
> > can import Heartbeats for non-Premium users back until their account was created.
> 
> I noticed that a few weeks ago, but I thought this is just a forgotten validation on endpoint :D

@allanvb Sadly, the feature (or bug) was fixed recently:(

But it may still be possible to import from wakapi so maybe a "instance API prefix" can be added on the import modal.

My log is attatched below:

```
hakatime  | ts=2024-10-20T11:47:17.800645566Z level=Info host=53f8347d0014 msg=processing import request for user "hijiajia" 
hakatime  | ts=2024-10-20T11:47:18.443715194Z level=Error host=53f8347d0014 msg=failed to execute import request 
hakatime  | ts=2024-10-20T11:47:18.443715194Z level=Error host=53f8347d0014 msg=http call to "wakatime.com" failed: StatusCodeException (Response {responseStatus = Status {statusCode = 402, statusMessage = "PAYMENT REQUIRED"}, responseVersion = HTTP/1.1, responseHeaders = [("Server","nginx"),("Date","Sun, 20 Oct 2024 11:47:18 GMT"),("Content-Type","application/json"),("Content-Length","82"),("Connection","keep-alive"),("Access-Control-Allow-Origin","*"),("X-Content-Type-Options","nosniff"),("Strict-Transport-Security","max-age=31536000; includeSubDomains; preload"),("X-XSS-Protection","1; mode=block"),("X-Frame-Options","SAMEORIGIN"),("Content-Security-Policy","default-src 'self'; frame-ancestors 'self'; script-src 'self' 'unsafe-eval' https://www.google.com/ https://www.gstatic.com/; img-src 'self' data: https://cdn.loom.com/; style-src 'self' 'unsafe-inline' https://fonts.googleapis.com/ https://fonts.gstatic.com/; font-src 'self' https://fonts.googleapis.com/ https://fonts.gstatic.com/; media-src 'self' https://*.amazonaws.com; frame-src 'self' https://www.google.com/ https://www.youtube.com/ https://www.loom.com/ player.vimeo.com; object-src 'self'; connect-src 'self' https://www.google.com/ https://avatar-cdn.atlassian.com;")], responseBody = (), responseCookieJar = CJ {expose = []}, responseClose' = ResponseClose, responseOriginalRequest = Request {
hakatime  |   host                 = "wakatime.com"
hakatime  |   port                 = 443
hakatime  |   secure               = True
hakatime  |   requestHeaders       = [("Authorization","<REDACTED>"),("Accept","application/json")]
hakatime  |   path                 = "/api/v1/users/current/heartbeats"
hakatime  |   queryString          = "?date=2024-10-10T00%3A00%3A00Z"
hakatime  |   method               = "GET"
hakatime  |   proxy                = Nothing
hakatime  |   rawBody              = False
hakatime  |   redirectCount        = 10
hakatime  |   responseTimeout      = ResponseTimeoutDefault
hakatime  |   requestVersion       = HTTP/1.1
hakatime  |   proxySecureMode      = ProxySecureWithConnect
hakatime  | }
hakatime  | }) "{\"error\": \"You\\u2019ve discovered a premium feature!\", \"show_upgrade_modal\": true}" 
```

**Comment by JesseHoekema** [comment]
This will be very usefull!
