### ISSUE TITLE
VSCode extension fails to send heartbeats when running docker-compose example

### ISSUE THREAD

**Issue by TommasoAmici** [mujx/hakatime#70]
I tried the demo instance with `api_url = https://hakatime.mtx-dev.xyz/api/v1/users/current/heartbeats.bulk` and it works as expected, however when running locally with `docker-compose -f ./docker-compose-deploy.yml up` the VSCode extension fails to register any heatbeat.

Settings

```text
[settings]
api_key = XXX
api_url = https://local.hakatime.com/api/v1/users/current/heartbeats.bulk
```

Error log:

```json
{
  "caller": "cmd/run.go:270",
  "file": "/Users/tommi/.wakatime.log",
  "func": "cmd.runCmd",
  "level": "error",
  "lineno": 1,
  "message": "failed to run command: sending heartbeat(s) failed: bad request: bad request at \"https://local.hakatime.com/api/v1/users/current/heartbeats.bulk\"",
  "now": "2022-12-03T13:17:22+01:00",
  "os/arch": "darwin/arm64",
  "plugin": "vscode/1.73.1 vscode-wakatime/22.0.1",
  "time": 1670069842.451042,
  "version": "v1.60.1"
}
```

**Comment by mujx** [comment]
@TommasoAmici Could you post here the docker-compose example you used? 

Note that `local.hakatime.com` is probably not pointing to your local instance. If you're using the `docker-compose-deploy.yml` file found on the repo then your `api_url` on the config should be the following:
```
# e.g api_url=https://hakatime.mtx-dev.xyz/api/v1/users/current/heartbeats.bulk for the demo instance.
api_url=http://localhost:8080/api/v1/users/current/heartbeats.bulk
```

**Comment by TommasoAmici** [comment]
Ok, I updated the version in the example file from `v1.6.1` to `v1.7.0-arm` (later versions don't seem to start on my M1 macbook) and it now works, thanks for the help!
