### ISSUE TITLE
Browser-Reload doesn't load the data again

### ISSUE THREAD

**Issue by lukasleitsch** [mujx/hakatime#8]
Accessing the page with the Root-Domain loads the data and redirect to the url `/#!/app`. After this step a browser reload doesn't work anymore. The page shows only the loading indicator. Happens in Chrome and Firefox.

If I remove `/#!/app` from the url the page loads without any issues.

If you need more information for debugging, please let me know.

**Comment by mujx** [comment]
Thanks for the bug report.

**Comment by lukasleitsch** [comment]
Thanks for the really quick fixing.

For me is pressing ⌘ + R the fastest way to refresh the data.
