### ISSUE TITLE
Date range picker for selecting the date range

### ISSUE THREAD

**Issue by lukasleitsch** [mujx/hakatime#9]
I have to admit that the time limit button confuse me. I don't understand the exactly behavior. I could imagine a date range picker with presets could solve the issue. With a date range picker we are not limit to the current presets (max. 90 days). II would be pleased about having stats about an entire year.

Many something like this: http://www.daterangepicker.com/

What do you think about ab date range picker?

**Comment by mujx** [comment]
I agree, a date picker will provider a more complete solution. 

Fyi there is already a date range picker library bundled in. It's used on the timeline chart by clicking on the 3-dot menu.

**Comment by lukasleitsch** [comment]
Awesome. Thanks for your work.
